{
 "title": "総合",
 "tags": [
  "remo",
  "temp",
  "amedas",
  "node_exporter",
  "lmsensors_exporter"
 ],
 "time": { "from": "2026-04-12T08:33:51.790Z", "to": "2026-04-12T20:33:51.790Z" },
 "templating": {
  "list": [
   {
    "name": "db_victoriametrics",
    "query": "victoriametrics-metrics-datasource"
   },
   { "name": "db_prometheus", "query": "prometheus" },
   { "name": "db_loki", "label": "db_loki", "query": "loki" },
   {
    "name": "remo_device",
    "query": {
     "query": "label_values(remo_temperature,instance)"
    }
   },
   {
    "name": "location",
    "query": {
     "query": "label_values(amedas_temperature,name_kana)"
    }
   },
   {
    "name": "node",
    "label": "instance",
    "query": {
     "query": "label_values(smartctl_device,instance)"
    }
   },
   {
    "name": "disk",
    "label": "device",
    "query": {
     "query": "label_values(smartctl_device,device)"
    }
   },
   {
    "name": "type",
    "label": "interface",
    "query": {
     "query": "label_values(smartctl_device,interface)"
    }
   },
   {
    "name": "serial_number",
    "label": "serial_number",
    "query": {
     "query": "label_values(smartctl_device,serial_number)"
    }
   },
   {
    "name": "device_model",
    "label": "model_name",
    "query": {
     "query": "label_values(smartctl_device,model_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "削除してね",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "#### 🛠️ 初期設定ガイド\nこのダッシュボードは汎用化のため、一部の変数を非表示にしています。  \n環境に合わせて表示を切り替えるには、左上の🖼️ **[ ||| +11 ]** 🖼️（または変数プルダウン）から以下の値を調整してください。\n\n* **location**: アメダスの地点名を選択\n* **remo_device**: Nature Remoのデバイス名を選択\n* **instance**: RemoExporterのサーバーホストを選択\n\n* **device**: SMART監視デバイス。sdaとかnvme0とか。全選択推奨\n* **interface**: 収集している端末のIP等。全選択推奨\n* **serial_number**: HDDなどのシリアル。全選択推奨\n* **model_name**: 型番。全選択推奨\n"
   }
  },
  {
   "title": "WARN log",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{level=~\"error|warn|fatal|crit|emerg\"} | json | label_format computer=\"{{.computer}}\", source=\"{{.source}}\", message=\"{{.message}}\"",
     "legendFormat": "computer, source, message"
    }
   ]
  },
  {
   "title": "☔アメダス-降水量/1時間",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amedas_precipitation_1h{name_kana=\"${location}\"}"
    }
   ]
  },
  {
   "title": "⛅️アメダス-気圧",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amedas_normal_pressure{name_kana=\"${location}\"}"
    }
   ]
  },
  {
   "title": "🌡️アメダス-温度",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amedas_temperature{name_kana=\"${location}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🌡️Remo-温度",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "remo_temperature{instance=\"${remo_device}\", __name__=\"remo_temperature\"}"
    }
   ]
  },
  {
   "title": "lm_sensors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(label_replace(lmsensors_temperature_degrees_celsius{sensor=\"temp1\"}, \"chip2\", \"$1\", \"device\", \"([^-]+?)-.*\"), \"inst2\", \"$1\", \"instance\", \"(?:192\\\\.168\\\\.)?([^.:]+).*\")",
     "legendFormat": "{{inst2}}_{{chip2}}"
    }
   ]
  },
  {
   "title": "node_thermal",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(label_replace(node_hwmon_temp_celsius{sensor=\"temp1\"}, \"chip2\", \"$1\", \"chip\", \"(?:0000:0)?(?:0:0[0-9]_)?(?:platform_)?(?:thermal_)?(?:nvme_)?([^_-]+)?.*\"), \"inst2\", \"$1$2\", \"instance\", \"(?:192\\\\.168\\\\.)?([0-9]*\\\\.)?([^.:]+).*\")",
     "legendFormat": "{{inst2}}_{{chip2}}"
    }
   ]
  },
  {
   "title": "🌀アメダス-風速",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amedas_wind{name_kana=\"${location}\"}"
    }
   ]
  },
  {
   "title": "💡Remo-明るさ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "remo_illumination{}/256" }
   ]
  },
  {
   "title": "☁アメダス-湿度",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amedas_humidity{name_kana=\"${location}\"}"
    }
   ]
  },
  {
   "title": "☁Remo-湿度",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{instance=\"${remo_device}\", __name__=\"remo_humidity\"}"
    }
   ]
  },
  {
   "title": "⧉ Unbound",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_query_types_total{job=\"unbound\"} > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(smartctl_device_temperature{instance=~\"$node\", device=~\"$disk\"} * on(instance, device) group_left(interface,serial_number,model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}) by (instance,device,model_name)",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "🚶Remo-人感センサ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 26 },
   "targets": [
    { "expr": "remo_motion{}" }
   ]
  },
  {
   "title": "Disk Lifetime",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "max by(instance, device, model_name) (smartctl_device_power_on_seconds{instance=~\"$node\", device=~\"$disk\"}) * on(instance, device) smartctl_device{interface=~\"$type\", serial_number=~\"$serial_number\", model_name=~\"$device_model\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(smartctl_device_power_cycle_count{instance=~\"$node\", device=~\"$disk\"} * on(instance, device) group_left(interface,serial_number,model_family,model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}) by (instance, device, model_name)",
     "legendFormat": "Power Cycles"
    }
   ]
  }
 ]
}