{
 "title": "Node Exporter ダッシュボード 2024-05-20 TenSunS 自動同期版",
 "description": "【日本語版】2024-05-20 更新。TenSunS による ECS 収集を基にしたダッシュボードです。自動同期方式で収集された ECS 情報フィールドに対応し、重要指標の表示を最適化しました。Grafana 10 の新しいスタイルで再構築し、ヘルススコアの概念を追加するとともに、総合的なリソース消費情報のグラフを多数追加しました。CPU、メモリ、ディスク、IO、ネットワークなどの監視指標を含みます。https://github.com/starsliao/TenSunS",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn",
  "TenSunS"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "db_victoriametrics",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "vendor",
    "label": "クラウドベンダー",
    "query": {
     "query": "label_values(node_uname_info, vendor)"
    }
   },
   {
    "name": "account",
    "label": "アカウント",
    "query": {
     "query": "label_values(node_uname_info{vendor=~\"$vendor\"}, account)"
    }
   },
   {
    "name": "group",
    "label": "グループ",
    "query": {
     "query": "label_values(node_uname_info{vendor=~\"$vendor\",account=~\"$account\"},group)"
    }
   },
   {
    "name": "name",
    "label": "名前",
    "query": {
     "query": "label_values(node_uname_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\"},name)"
    }
   },
   {
    "name": "instance",
    "label": "IP",
    "query": {
     "query": "label_values(node_uname_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\"},instance)"
    }
   },
   { "name": "interval", "label": "間隔", "query": "3m" },
   {
    "name": "total",
    "label": "合計",
    "query": {
     "query": "query_result(count(node_uname_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}))"
    }
   },
   {
    "name": "device",
    "label": "デバイス",
    "query": {
     "query": "label_values(node_network_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",instance=~\"$instance\",device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
    }
   },
   {
    "name": "maxmount",
    "label": "最大マウント",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",instance=~\"$instance\",fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   },
   {
    "name": "show_name",
    "label": "表示名",
    "query": {
     "query": "label_values(node_uname_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",instance=~\"$instance\"}, name)"
    }
   },
   {
    "name": "iid",
    "label": "ID",
    "query": {
     "query": "label_values(node_uname_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\"},iid)"
    }
   },
   { "name": "sname", "label": "名前" }
  ]
 },
 "panels": [
  {
   "title": "🏡リソース概要：選択中ホスト：$show_name、インスタンス：$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "サーバーリソース一覧【グループ：$group、ホスト数：$total】",
   "type": "table",
   "description": "パーティション使用率、ディスク読み取り、ディスク書き込み、ダウンロード帯域幅、アップロード帯域幅。複数のNICやパーティションがある場合、最も使用率が高いものの値を取得します。\n\n接続数：CurrEstab - 現在の状態が ESTABLISHED または CLOSE-WAIT の TCP 接続数。\n\nヘルス値は新しい指標で、CPU、メモリ、IOから算出されます。90点未満の場合はシステムリソースの使用状況に注意が必要です。これはテスト中の指標で、パラメータは実際の状況に応じて最適化が必要です。",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_uname_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"} - 0",
     "legendFormat": "ホスト名"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"})by(instance)/86400",
     "legendFormat": "稼働時間"
    },
    {
     "expr": "node_memory_MemTotal_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"} - 0",
     "legendFormat": "総メモリ"
    },
    {
     "expr": "count(node_cpu_seconds_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",mode='system',name=~\".*$sname.*\"}) by (instance)",
     "legendFormat": "総コア数"
    },
    {
     "expr": "node_load5{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}",
     "legendFormat": "5分間負荷"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",mode=\"idle\",name=~\".*$sname.*\"}[$interval])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"} / (node_memory_MemTotal_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"})))* 100",
     "legendFormat": "メモリ使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "パーティション使用率"
    },
    {
     "expr": "max(irate(node_disk_read_bytes_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[$interval])) by (instance)",
     "legendFormat": "最大読み取り"
    },
    {
     "expr": "max(irate(node_disk_written_bytes_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[$interval])) by (instance)",
     "legendFormat": "最大書き込み"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"} - 0",
     "legendFormat": "接続数"
    },
    {
     "expr": "node_sockstat_TCP_tw{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(irate(node_network_receive_bytes_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[$interval])*8) by (instance)",
     "legendFormat": "ダウンロード帯域幅"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[$interval])*8) by (instance)",
     "legendFormat": "アップロード帯域幅"
    },
    {
     "expr": "((1-(1 - avg(irate(node_cpu_seconds_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",mode=\"idle\"}[$interval])) by (instance))^1.3)^(1/3)*0.5 + \r\n(1-(1 - avg(node_memory_MemAvailable_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"} / node_memory_MemTotal_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"})by (instance))^6)^(1/3)*0.3 + \r\n(1 - max(irate(node_disk_io_time_seconds_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[$interval]))by (instance)^1.1)^(1/2)*0.2)*100",
     "legendFormat": "健康スコア"
    },
    {
     "expr": "max(irate(node_disk_io_time_seconds_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[$interval])) by (instance) *100",
     "legendFormat": "IOutil使用率"
    }
   ]
  },
  {
   "title": "過去7日間のP99リソース使用率",
   "type": "table",
   "description": "- P99：データセットを昇順に並べ替え、99パーセンタイルに位置する大きなデータ。（すなわち、昇順に並べ替えた後に99％の位置にあるデータ）\n- このテーブルにはPrometheusに記録ルールを追加する必要があります（ダッシュボードのダウンロードページを参照）\n- 収集開始から1時間後にデータが表示されます\n- 時間範囲[7d:1h]は、過去7日間の1時間ごとのデータポイントを表示することを意味します。",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "node_uname_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"} - 0",
     "legendFormat": "ホスト名"
    },
    {
     "expr": "quantile_over_time(0.99, cpu:usage:rate1m{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[7d:1h])",
     "legendFormat": "CPU使用率P99"
    },
    {
     "expr": "quantile_over_time(0.99, mem:usage:rate1m{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[7d:1h])",
     "legendFormat": "メモリ使用率P99"
    }
   ]
  },
  {
   "title": "全体の総負荷と平均CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(node_load5{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\".*$sname.*\",name=~\"$name\"})",
     "legendFormat": "5分間負荷"
    },
    {
     "expr": "count(node_cpu_seconds_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",mode='system'})",
     "legendFormat": "コア数"
    },
    {
     "expr": "avg(1 - avg(irate(node_cpu_seconds_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "平均%"
    }
   ]
  },
  {
   "title": "全体メモリと平均メモリ使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"} - node_memory_MemAvailable_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"})",
     "legendFormat": "総使用量"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"})",
     "legendFormat": "総メモリ"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"} - node_memory_MemAvailable_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}) / sum(node_memory_MemTotal_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}))*100",
     "legendFormat": "総平均%"
    }
   ]
  },
  {
   "title": "全体ディスクと平均ディスク使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "総使用量"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "総ディスク容量"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance))) *100/(sum(avg(node_filesystem_avail_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance))+(sum(avg(node_filesystem_size_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"xfs|ext.*\"})by(device,instance))))",
     "legendFormat": "平均%"
    }
   ]
  },
  {
   "title": "🧮リソース詳細：【$show_name】【$instance】【$iid】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "【$show_name】：パーティション利用可能容量(EXT.*/XFS/NFS)",
   "type": "table",
   "description": "このダッシュボードのディスク総容量、使用量、空き容量、使用率は、dfコマンドのSize、Used、Avail、Use%列の値と一致します。また、Use%の値は小数点第1位で四捨五入されるため、より正確です。\n\n注：dfコマンドのUse%の計算式は：(size - free) * 100 / (avail + (size - free)) です。割り切れる場合はその値、割り切れない場合はその値+1となり、単位は%です。\ndfコマンドのソースコードを参照：",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "総容量"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "総CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"} / (node_memory_MemTotal_bytes{instance=~\"$instance\"})))* 100",
     "legendFormat": "メモリ使用率"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "最大パーティション使用率({{mountpoint}})"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$instance\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$instance\"} + 1))) * 100",
     "legendFormat": "スワップ使用率"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(time() - node_boot_time_seconds{instance=~\"$instance\"})",
     "legendFormat": "稼働時間",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "count(node_cpu_seconds_total{instance=~\"$instance\", mode='system'})",
     "legendFormat": "CPU コア数",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\"})",
     "legendFormat": "総メモリ",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[$interval])) * 100",
     "legendFormat": "CPU iowait",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "node_filefd_maximum{instance=~\"$instance\"}",
     "legendFormat": "総ファイルディスクリプタ",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "process_max_fds{job=\"node_exporter\",instance=~\"$instance\"}",
     "legendFormat": "最大オープンファイル数",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$device の毎分トラフィック",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=~\"$instance\",device=~\"$device\"}[1m])",
     "legendFormat": "{{device}}_inダウンロード"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=~\"$instance\",device=~\"$device\"}[1m])",
     "legendFormat": "{{device}}_outアップロード"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "総使用率"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "システム使用率"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "ユーザ使用率"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "ディスクIO使用率"
    }
   ]
  },
  {
   "title": "メモリ情報",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "利用可能"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "総メモリ"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "使用済み"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"} / (node_memory_MemTotal_bytes{instance=~\"$instance\"})))* 100",
     "legendFormat": "使用率"
    }
   ]
  },
  {
   "title": "ディスク使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "容量%：{{mountpoint}}"
    },
    {
     "expr": "(1 - node_filesystem_files_free{instance=~\"$instance\",fstype=~\"ext.?|xfs|nfs\",mountpoint !~\".*pod.*\"} / node_filesystem_files{instance=~\"$instance\",fstype=~\"ext.?|xfs|nfs\",mountpoint !~\".*pod.*\"}) * 100",
     "legendFormat": "Inodes%：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "システム平均ロード",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}",
     "legendFormat": "1分間負荷"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{instance=~\"$instance\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPU総コア数"
    },
    {
     "expr": "node_load5{instance=~\"$instance\"}",
     "legendFormat": "5分間負荷"
    },
    {
     "expr": "node_load15{instance=~\"$instance\"}",
     "legendFormat": "15分間負荷"
    }
   ]
  },
  {
   "title": "プロセス稼働状況",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_running{instance=~\"$instance\"}",
     "legendFormat": "実行中のプロセス",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_blocked{instance=~\"$instance\"}",
     "legendFormat": "I/O待ちでブロックされているプロセス",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_blocked%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "ファイルディスクリプタ(FD) / 秒間コンテキストスイッチ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "秒間コンテキストスイッチ"
    },
    {
     "expr": "node_filefd_allocated{instance=~\"$instance\"}",
     "legendFormat": "総使用FD"
    },
    {
     "expr": "(node_filefd_allocated{instance=~\"$instance\"}/node_filefd_maximum{instance=~\"$instance\"}) *100",
     "legendFormat": "総使用FD割合"
    },
    {
     "expr": "(process_open_fds{instance=~\"$instance\"}/process_max_fds{instance=~\"$instance\"}) *100",
     "legendFormat": "进程使用FD割合"
    }
   ]
  },
  {
   "title": "IOごとの読み書き所要時間（参考：100ms未満）",
   "type": "timeseries",
   "description": "Read time seconds: 各ディスクパーティションの読み取り操作に費やされた秒数\n\nWrite time seconds: 各ディスクパーティションの書き込み操作に費やされた秒数\n\nIO time seconds: 各ディスクパーティションの入出力操作に費やされた秒数\n\nIO time weighted seconds: 各ディスクパーティションの入出力操作に費やされた加重秒数",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$instance\"}[$interval]) / irate(node_disk_reads_completed_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_読み取り"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$instance\"}[$interval]) / irate(node_disk_writes_completed_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_書き込み"
    }
   ]
  },
  {
   "title": "ディスク読み書き速度（IOPS）",
   "type": "timeseries",
   "description": "Reads completed: 各ディスクパーティションの1秒あたりの読み取り完了回数\n\nWrites completed: 各ディスクパーティションの1秒あたりの書き込み完了回数\n\nIO now: 各ディスクパーティションで現在処理中の入出力リクエスト数",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_読み取り"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_書き込み"
    }
   ]
  },
  {
   "title": "秒間ディスク読み書き容量",
   "type": "timeseries",
   "description": "Read bytes: 各ディスクパーティションの1秒あたりの読み取りバイト数\nWritten bytes: 各ディスクパーティションの1秒あたりの書き込みバイト数",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_読み取り"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_書き込み"
    }
   ]
  },
  {
   "title": "1秒あたりのI/O操作時間の割合（I/O Util）",
   "type": "timeseries",
   "description": "1秒間の実時間のうち、I/Oに費やされた時間。（wall-clock time）\n\nnode_disk_io_time_seconds_total：\nディスクが入出力操作に費やした秒数。この値は累積値です。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n秒間のレートを計算します：(最新の値 - 直前の値) / タイムスタンプの差。すなわち、1秒間のうちにディスクがI/O操作に費やした時間の割合です。",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{device}}_秒間I/O操作%"
    }
   ]
  },
  {
   "title": "ネットワークソケット接続情報",
   "type": "timeseries",
   "description": "Sockets_used - 使用されているすべてのプロトコルソケットの総量\n\nCurrEstab - 現在の状態が ESTABLISHED または CLOSE-WAIT の TCP 接続数\n\nTCP_alloc - 割り当て済み（確立済み、sk_buff取得済み）のTCPソケット数\n\nTCP_tw - クローズ待ちのTCP接続数\n\nUDP_inuse - 使用中のUDPソケット数\n\nRetransSegs - TCP再送パケット数\n\nOutSegs - TCP送信パケット数\n\nInSegs - TCP受信パケット数",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$instance\"}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"$instance\"}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~\"$instance\"}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~\"$instance\"}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~\"$instance\"}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "irate(node_netstat_Tcp_InSegs{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  },
  {
   "title": "$device の毎秒ネットワーク帯域使用",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$instance\",device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_inダウンロード"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$instance\",device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_outアップロード"
    }
   ]
  }
 ]
}