"$schema" = 'https://starship.rs/config-schema.json'

#[░▒▓](#a3aed2)\
#[  ](bg:#a3aed2 fg:#090c0c)\

format = """
$hostname\
[](bg:#466fc0 fg:#a3aed2)\
(bg:#a3aed2 fg:#090c0c)\
$directory\
[](fg:#466fc0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
$cmd_duration\
[ ](fg:#1d2230)\
$sudo\
\n$character"""

[cmd_duration]
show_milliseconds = true
format = '[[  $duration ](fg:#a98888 bg:#1d2230)]($style)'
style = "fg:rosewater"
disabled = false
show_notifications = true
min_time_to_notify = 45000
min_time = 700

[hostname]
ssh_only = false
format = "[$os$hostname](bg:#a3aed2 fg:#090c0c)"
disabled = false

[directory]
style = "fg:#ffffff bg:#466fc0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%H:%M:%S"
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
